<?php

echo $block->alo();

?>

<h2>Add Post Forms</h2>

<form action="/blog/post/save" method="POST">

    <div class="form-group">
        <label for="name">Title : </label>
        <input type="text" class="form-control" name="title">
    </div>
    <br>
    <div class="form-group">
        <label for="phone">Content :</label>
        <input type="text" class="form-control" name="content">
    </div>
    <br>

  <button type="submit" name="createbtn" class="btn btn-primary" >Submit</button>

</form>


