
<h2>Edit Post Forms</h2>

<form action="/blog/post/save" method="POST">
    <input type="hidden" name="id" value="<?php echo $block->getPost()->getId(); ?>">

    <div class="form-group">
        <label for="name">Title : </label>
        <input type="text" class="form-control" value="<?php echo $block->getPost()->getTitle(); ?>" name="title">
    </div>
    <br>
    <div class="form-group">
        <label for="phone">Content :</label>
        <input type="text" class="form-control" value="<?php echo $block->getPost()->getContent(); ?>" name="content">
    </div>
    <br>

  <button type="submit" name="editbtn" class="btn btn-primary">Submit</button>

</form>


