
<h2>Edit Post Forms</h2>

<form action="" method="post">

  <label for="title">Title : </label><br>
  <input type="text" name="title" value="<?php echo $block->getPost()->getTitle(); ?>"><br>

  <label for="content">Content :</label><br>
  <input type="text" name="content" value="<?php echo $block->getPost()->getContent(); ?>"><br><br>

</form>

<button type="submit" class="btn btn-primary" form="form1" value="Submit">Submit</button>
