<style>
    table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    }
    .edit:link, .edit:visited,
    .delete:link, .delete:visited {
    color: white;
    padding: 14px 25px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    }

    .edit:link, .edit:visited {
        background-color: #2489cc;
    }

    .delete:link, .delete:visited {
        background-color: #f44336;
    }

    .edit:hover, .edit:active {
        background-color: #006bb4;
    }

    .delete:hover, .delete:active {
    background-color: red;
    }
</style>

<?php

echo $block->sayHello();

?>

<h1>Posts</h1>

<div>
<a class="edit" href="<?php echo $block->getCreatePostUrl(); ?>" target="_blank" rel="noopener noreferrer">Add a Post</a>
</div> <br>

<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Content</th>
    <th>Create at</th>
    <th>Action</th>
  </tr>
  <?php foreach($block->getPosts() as $post): ?>
    <?php /** @var Modulevip\Blog\Model\Post */ ?>
  <tr>
    <td><?php echo $post->getId(); ?></td>
    <td><?php echo $post->getTitle(); ?></td>
    <td><?php echo $post->getContent(); ?></td>
    <td><?php echo $post->getCreatedAt(); ?></td>
    <td>
        <a class="edit" href="<?php echo $block->getPostUrl($post);?>" target="_blank">Edit</a>
        <a onclick='return confirmDel()' class="delete" href="<?php echo $block->getDelPostUrl($post);?>">Delete</a>
    </td>
  </tr>
  <?php endforeach; ?>
</table>


<script>
        function confirmDel() {
            return confirm("Đồng ý xóa ?");
        }
</script>
